version: "3.8"

services:
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./.volumes/cache:/data